# Generated by Django 5.2.6 on 2025-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlist_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='movie_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
